export * from "./navbar";
export * from "./hero";
export * from "./partners";
export * from "./commitments";
export * from "./work";
export * from "./cta-banner";
export * from "./team";
export * from "./bottom";
export * from "./footer";
